/* Settings control center smoke test. No network. */
const fs = require('fs'), path = require('path'); const { JSDOM } = require('./vendor/jsdom.bundle.js');
const ROOT = path.join(__dirname, '..'); let pass = 0, fail = 0;
const ok = (n, c) => { if (c) { pass++; console.log(' ok  ', n); } else { fail++; console.log('FAIL', n); } };
(async () => {
  const html = fs.readFileSync(path.join(ROOT, 'dashboard.html'), 'utf8').replace(/<script[\s\S]*?<\/script>/g, '');
  const dom = new JSDOM(html, { url: 'https://dashview.example/dashboard.html', runScripts: 'outside-only', pretendToBeVisual: true });
  const w = dom.window, d = w.document;
  const releaseManifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'version.json'), 'utf8'));
  w.fetch = async () => ({ ok: true, json: async () => releaseManifest });
  w.DVOdoo = { isConnected: () => false };
  w.DVAIConfig = { get: () => ({ provider: 'anthropic' }), isConfigured: () => false };
  w.DVSec = { checkup: () => ({ score: 55, items: [{ ok: false, label: 'Passcode lock is on', weight: 25, hint: 'Set a passcode.' }, { ok: true, label: 'HTTPS', weight: 15 }] }) };
  w.eval(fs.readFileSync(path.join(ROOT, 'js/settings-overview.js'), 'utf8'));
  if (d.readyState === 'loading') await new Promise((r) => d.addEventListener('DOMContentLoaded', r));
  await new Promise((r) => setTimeout(r, 200));
  const c = d.getElementById('stgoCenter');
  ok('control center is injected', !!c && c.querySelectorAll('.stgo-card').length === 5);
  ok('shows Odoo not connected, AI setup needed, security score', /Not connected/.test(c.textContent) && /Setup needed/.test(c.textContent) && /55\/100/.test(c.textContent));
  ok('Needs attention lists actionable items with hints', /Needs attention/.test(c.textContent) && /Passcode lock is off/.test(c.textContent) && /Set a passcode/.test(c.textContent));
  ok('version loaded from version.json', /v2\.8\.0/.test(c.textContent));
  const versionCard = c.querySelector('[data-version-notes]');
  versionCard.click();
  ok('clicking the version card opens release history', !!d.getElementById('stgoReleaseDialog') && /2\.8\.0/.test(d.getElementById('stgoReleaseDialog').textContent) && /2\.7\.0/.test(d.getElementById('stgoReleaseDialog').textContent));
  const todo = c.querySelector('.stgo-todo');
  todo.querySelector('summary').click();
  await new Promise((r) => setTimeout(r, 100));
  ok('Needs attention disclosure stays open after click and async refresh', todo.open && c.querySelector('.stgo-todo[open]'));
  let clicked = null; d.querySelector('.stg-tab[data-stg="odoo"]').addEventListener('click', () => { clicked = 'odoo'; });
  c.querySelector('[data-go="odoo"]').click();
  ok('card click jumps to its settings tab', clicked === 'odoo');
  d.querySelector('.stg-tab[data-stg="security"]').addEventListener('click', () => { clicked = 'security'; });
  c.querySelector('.stgo-todo [data-go="security"]').click();
  ok('Fix action routes to Security without closing the disclosure', clicked === 'security' && c.querySelector('.stgo-todo[open]'));
  const inp = d.getElementById('stgoSearch'); inp.value = 'passcode'; inp.dispatchEvent(new w.Event('input'));
  ok('search highlights matching cards and reports count', !!d.querySelector('.stgo-hit') && /match/.test(d.getElementById('stgoCount').textContent));
  inp.value = ''; inp.dispatchEvent(new w.Event('input'));
  ok('clearing search removes highlighting', !d.querySelector('.stgo-hit') && !d.querySelector('.stgo-dim'));
  const fullSettings = fs.readFileSync(path.join(ROOT, 'settings.html'), 'utf8');
  const manual = fs.readFileSync(path.join(ROOT, 'manual.html'), 'utf8');
  const appearancePanel = d.getElementById('stg-appearance');
  ok('main Settings keeps theme, accent, surface and dashboard preferences in the Appearance panel', appearancePanel.querySelector('#setThemeSelect') && appearancePanel.querySelector('#setAccentSelect') && appearancePanel.querySelector('#surfaceStyleOpts') && appearancePanel.querySelector('#setLandingSelect'));
  ok('main Settings includes install, offline and privacy controls in Data & backup', !!d.querySelector('#stg-data #installDesktopBtn') && !!d.querySelector('#stg-data #offlineStatusMsg') && !!d.querySelector('#stg-data #clearTempCacheBtn'));
  ok('main Settings provides reset preferences and the user manual in its own section', !!d.getElementById('resetSettingsBtn') && !!d.querySelector('.stg-tab[data-stg="help"]') && !!d.querySelector('#stg-help iframe[title="DashView user manual"]'));
  ok('manual documents company-aware Operations, record search/paging, and bounded drill exports', /Operations &amp; fulfilment/.test(manual) && /Previous\/Next loads 25 records/.test(manual) && /up to 10,000/.test(manual));
  ok('main Settings version display opens release notes', !!d.querySelector('#verAppVersion[title="View release notes"]'));
  ok('main Settings does not route users to a separate More settings page', !appearancePanel.querySelector('a[href^="settings.html"]'));
  ok('extended preferences remain available in the standalone Settings fallback', ['appearance', 'accessibility', 'prefs', 'updates', 'privacy', 'app', 'backup'].every((id) => new RegExp('id="' + id + '"').test(fullSettings)));
  w.localStorage.setItem('dashview-theme', 'dark');
  w.localStorage.setItem('dashview-config', JSON.stringify({ theme: 'dark', accent: 'blue', motion: 'reduce' }));
  w.localStorage.setItem('dashview_surface', 'glass');
  w.localStorage.setItem('dv-pref-density', 'compact');
  w.localStorage.setItem('dv-pref-anim', 'off');
  w.localStorage.setItem('dv-pref-labels', 'off');
  w.localStorage.setItem('dv-pref-landing', 'ai');
  w.localStorage.setItem('dashview_odoo_config', JSON.stringify({ url: 'https://odoo.example', apiKey: 'keep-me' }));
  w.localStorage.setItem('dashview_workbooks', JSON.stringify([{ name: 'keep workbook' }]));
  w.confirm = () => true;
  w.eval(fs.readFileSync(path.join(ROOT, 'js/config.js'), 'utf8'));
  w.eval(fs.readFileSync(path.join(ROOT, 'js/settings-pro.js'), 'utf8'));
  d.getElementById('resetSettingsBtn').click();
  ok('Reset preferences restores appearance defaults and keeps Odoo and workbook data', w.DV.get().theme === 'system' && w.DV.get().accent === 'amber' && w.DV.get().motion === 'system' && w.localStorage.getItem('dashview_surface') === 'flat' && !!w.localStorage.getItem('dashview_odoo_config') && !!w.localStorage.getItem('dashview_workbooks'));
  ok('Reset preferences clears saved dashboard choices and synchronizes visible controls', ['density', 'anim', 'labels', 'landing'].every((key) => !w.localStorage.getItem('dv-pref-' + key)) && d.getElementById('setDensitySelect').value === 'comfortable' && d.getElementById('setChartAnimSelect').value === 'on' && d.getElementById('setChartLabelsSelect').value === 'on' && d.getElementById('setLandingSelect').value === 'overview');
  ok('Settings keeps a readable bundled version number without service-worker support', /DashView 2\.8\.0/.test(d.getElementById('verAppVersion').textContent) && !/DashView -/.test(d.getElementById('verAppVersion').textContent));
  w.close(); console.log(`${pass} passed, ${fail} failed`); process.exitCode = fail ? 1 : 0;
})().catch((e) => { console.error(e); process.exit(1); });
