/* Software Update flow: available banner -> download -> ready -> install */
const { JSDOM } = require('./vendor/jsdom.bundle.js'); const fs = require('fs'); const path = require('path'); const assert = require('assert');
const src = fs.readFileSync(path.join(__dirname, '..', 'js', 'updater.js'), 'utf8');
const dom = new JSDOM('<body></body>', { url: 'https://dash.test/', runScripts: 'outside-only', pretendToBeVisual: true });
const w = dom.window; let remote = { version: '2.0.0', build: 'b', notes: ['one'], history: [] }; const posted = [];
let workerMessage;
let updateFails = false;
const reg = { waiting: null, update: () => updateFails ? Promise.reject(new Error('fetch failed')) : Promise.resolve(), };
w.DV = {}; w.fetch = (u) => Promise.resolve({ ok: true, json: () => Promise.resolve(/latest=/.test(u) ? remote : { version: '1.0.0', build: 'a', notes: [], history: [] }) });
Object.defineProperty(w.navigator, 'serviceWorker', { value: { addEventListener(name, fn) { if (name === 'message') workerMessage = fn; }, getRegistration: () => Promise.resolve(reg) } });
w.eval(src);
const U = w.DV.updater, wait = (ms) => new Promise(r => setTimeout(r, ms));
(async () => {
  await wait(50);
  assert.strictEqual(U.state().phase, 'idle');
  await U.check(false);
  assert.strictEqual(U.state().phase, 'available', 'newer version.json -> available');
  const bn = w.document.querySelector('.dvb'); assert(bn && /Update available/.test(bn.textContent) && /Download/.test(bn.textContent), 'top banner with Download');
  assert.strictEqual(bn.querySelector('[role="progressbar"]').getAttribute('aria-valuenow'), '0', 'banner progress has an accessible value');
  const opener = w.document.createElement('button'); opener.textContent = 'Open updates'; w.document.body.appendChild(opener); opener.focus();
  U.open(); await wait(20);
  assert(w.document.querySelector('.dvu .dvu-steps') && w.document.querySelector('.dvu .dvu-grp'), 'details sheet shows stepper and grouped release notes');
  assert(/Download update/.test(w.document.querySelector('.dvu').textContent), 'sheet offers Download update');
  const dialog = w.document.querySelector('.dvu');
  assert.strictEqual(dialog.getAttribute('role'), 'dialog', 'update sheet is announced as a dialog');
  assert.strictEqual(dialog.getAttribute('aria-modal'), 'true', 'update sheet is modal');
  assert(dialog.getAttribute('aria-labelledby') && dialog.getAttribute('aria-describedby'), 'dialog has an accessible name and description');
  assert.strictEqual(w.document.activeElement.id, 'u-dl', 'opening the dialog moves focus to its primary action');
  const outside = w.document.createElement('button'); outside.textContent = 'Outside'; w.document.body.appendChild(outside); outside.focus();
  outside.dispatchEvent(new w.KeyboardEvent('keydown', { key: 'Tab', bubbles: true }));
  assert(dialog.contains(w.document.activeElement), 'Tab cannot move focus outside the modal');
  const focusables = [...dialog.querySelectorAll('button:not([disabled]),summary,a[href]')];
  focusables[0].focus();
  focusables[0].dispatchEvent(new w.KeyboardEvent('keydown', { key: 'Tab', shiftKey: true, bubbles: true }));
  assert.strictEqual(w.document.activeElement, focusables[focusables.length - 1], 'Shift+Tab wraps within the dialog');
  w.document.querySelector('#u-x').click(); assert(!w.document.querySelector('.dvu'), 'Close dismisses the sheet');
  assert.strictEqual(w.document.activeElement, opener, 'closing the dialog restores focus to its opener');
  U.notes(); await wait(20); assert(/Release notes/.test(w.document.querySelector('.dvu').textContent), 'notes() opens release notes');
  w.document.querySelector('.dvu').dispatchEvent(new w.KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
  assert(!w.document.querySelector('.dvu'), 'Escape dismisses a non-busy dialog');
  U.download(); await wait(50);
  assert.strictEqual(U.state().phase, 'downloading');
  U.open(); await wait(10);
  const progress = w.document.querySelector('.dvu [role="progressbar"]');
  assert(progress && Number(progress.getAttribute('aria-valuenow')) > 0, 'download dialog exposes live progress');
  assert(w.document.querySelector('.dvu-step[aria-live="polite"]'), 'progress status is announced politely');
  const updaterCss = w.document.getElementById('dvu-css').textContent;
  assert(/prefers-reduced-motion:reduce/.test(updaterCss), 'updater styles honor reduced-motion preferences');
  assert(/max-width:420px/.test(updaterCss) && /safe-area-inset-bottom/.test(updaterCss), 'update dialog has compact, safe-area-aware mobile styling');
  w.document.querySelector('.dvu').dispatchEvent(new w.KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
  assert(w.document.querySelector('.dvu'), 'Escape cannot dismiss an active download');
  workerMessage({ data: { type: 'dv-update-failed', message: 'Precache failed.' } }); await wait(20);
  assert.strictEqual(U.state().phase, 'failed', 'service worker precache failure immediately becomes a retryable update error');
  assert(/Precache failed/.test(w.document.querySelector('.dvb').textContent), 'update failure is explained in the banner');
  assert(w.document.querySelector('.dvu [role="alert"]') && /Retry download/.test(w.document.querySelector('.dvu').textContent), 'dialog presents an announced error and retry action');
  updateFails = true; U.download(); await wait(20);
  assert.strictEqual(U.state().phase, 'failed', 'update-server errors immediately become retryable instead of being swallowed');
  assert(/update server/.test(w.document.querySelector('.dvb').textContent), 'update-server failure is explained in the banner');
  updateFails = false;
  U.download(); await wait(50);
  assert.strictEqual(U.state().phase, 'downloading', 'failed update can be retried');
  reg.waiting = { postMessage: (m) => posted.push(m) }; await wait(450);
  assert.strictEqual(U.state().phase, 'ready', 'worker waiting -> ready');
  assert(/Install/.test(w.document.querySelector('.dvb').textContent), 'banner offers Install & Restart');
  assert.strictEqual(posted.length, 0, 'the waiting worker is not activated automatically');
  U.open();
  const installButton = w.document.querySelector('.dvu #u-in');
  assert(installButton && /Install & Restart/.test(installButton.textContent), 'ready dialog presents the explicit install action');
  assert.strictEqual(w.document.querySelector('.dvb [role="progressbar"]').getAttribute('aria-valuenow'), '100', 'ready banner reports completed download progress');
  installButton.click();
  assert.strictEqual(w.document.querySelector('.dvu [role="progressbar"]').getAttribute('aria-valuenow'), '80', 'installing dialog exposes its progress accessibly');
  await wait(1500);
  assert.deepStrictEqual(posted, ['skip'], 'install sends skip to the waiting worker');
  console.log('Updater flow smoke tests passed.'); process.exit(0);
})().catch(e => { console.error(e); process.exit(1); });
