/* DashView service worker — makes the app work offline.
   Bump VERSION on release; the file list below is generated by the build step. */
var VERSION = 'dv-2.16.1';
var PRECACHE = [
 "index.html",
 "dashboard.html",
 "people.html",
 "ai.html",
 "share.html",
 "settings.html",
 "manual.html",
 "data-studio.html",
 "404.html",
 "manifest.json",
 "version.json",
 "js/updater.js",
 "css/ai-embed.css",
 "css/ai-assistant.css",
 "css/ai-page.css",
 "css/base.css",
 "css/visual-polish.css",
 "css/chart-polish.css",
 "css/overview-charts-pro.css",
 "css/pro-detail.css",
 "css/assistant.css",
 "css/index-pro.css",
 "css/index-glass.css",
 "js/index-demo.js",
 "css/landing.css",
 "css/navbar.css",
 "css/components.css",
 "css/dashboard-hr-match.css",
 "css/dashboard-pro.css",
 "css/dashboard.css",
 "css/dashview-suite.css",
 "css/merged.css",
 "css/odoo-live.css",
 "css/odoo-pro.css",
 "css/pro-upgrade.css",
 "css/security.css",
 "css/studio-dash.css",
 "css/studio-workspace.css",
 "css/studio.css",
 "js/ai-api-config.js",
 "js/ai-assistant.js",
 "js/ai-company-context.js",
 "js/ai-config-store.js",
 "js/ai-conversation-context.js",
 "js/ai-embed.js",
 "js/ai-files.js",
 "js/ai-odoo-agent.js",
 "js/ai-engine.js",
 "js/ai-page.js",
 "js/ai-settings-ui.js",
 "js/assistant.js",
 "js/app.js",
 "js/audit-live.js",
 "js/auth-service.js",
 "js/config.js",
 "js/dashboard-pro.js",
 "js/dashboard-data.js",
 "js/dashboard-import.js",
 "js/dashboard-builder.js",
 "js/dashboard.js",
 "js/dashview-dashboard.js",
 "js/dashview-api.js",
 "js/dv-security.js",
 "js/landing.js",
 "js/main.js",
 "js/odoo-client.js",
 "js/odoo-connectivity.js",
 "js/odoo-live.js",
 "js/odoo-profiles.js",
 "js/odoo-service.js",
 "js/overview-live.js",
 "js/people-shell.js",
 "js/report-engine.js",
 "js/security-ui.js",
 "js/shell.js",
 "js/studio.js",
 "js/studio-core.js",
 "js/studio-ui.js",
 "js/studio-reconcile.js",
 "js/studio-reconcile-ui.js",
 "js/tasks.js",
 "js/widget-builder.js",
 "assets/favicon.svg",
 "assets/favicon-32x32.png",
 "assets/apple-touch-icon.png",
 "assets/icon-192.png",
 "assets/icon-512.png",
 "assets/icon-maskable-192.png",
 "assets/icon-maskable-512.png",
 "css/exec-company.css",
 "css/exec-drill.css",
 "css/exec-errors.css",
 "css/exec-unify.css",
 "css/exec-retail.css",
 "css/glass.css",
 "css/globals.css",
 "css/hero.css",
 "css/liquid-glass.css",
 "css/responsive.css",
 "css/settings-pro.css",
 "css/tabbar.css",
 "css/workspace.css",
 "js/auth.js",
 "js/boomerang-video.js",
 "js/exec-company.js",
 "js/exec-drill.js",
 "js/exec-errors.js",
 "js/exec-retail.js",
 "js/github-config.js",
 "js/github-live.js",
 "js/settings-pro.js",
 "js/tabbar.js",
 "overview.html",
 "js/settings-overview.js",
 "css/ws.css",
 "js/ws-store.js",
 "js/people.js",
 "css/hr-live.css",
 "css/people-pro.css",
 "css/people.css",
 "js/hr-app.js",
 "js/hr-icons.js",
 "js/hr-store.js",
 "js/hr-views.js",
 "js/odoo-hr.js",
 "js/odoo-targets.js",
 "js/people-live.js",
 "js/people-odoo-live.js",
 "css/theme-final.css",
 "login.html",
 "css/landing-glass.css",
 "css/landing-pro.css",
 "css/login.css",
 "js/index-glass.js",
 "css/audit-pro.css",
 "css/cursor.css",
 "css/studio-pro.css",
 "js/cursor.js",
 "js/studio-profile.js",
 "css/8k-quality.css",
 "js/8k-quality.js"
];
var CDN = /^https:\/\/(cdn\.jsdelivr\.net|cdnjs\.cloudflare\.com|fonts\.googleapis\.com|fonts\.gstatic\.com)\//;

/* Updates are GATED: a new worker downloads quietly (install) and then WAITS.
   Nothing changes for the user until they tap "Install Now" in the update
   sheet (js/updater.js), which sends 'skip'. Until then the installed version
   keeps serving every page and file from its own cache. */
self.addEventListener('install', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    var cacheExists = keys.indexOf(VERSION) !== -1;
    return caches.open(VERSION).then(function (c) {
      var done = 0, total = PRECACHE.length;
      function tell() {
        self.clients.matchAll({ includeUncontrolled: true }).then(function (cs) {
          cs.forEach(function (x) { x.postMessage({ type: 'dv-progress', done: done, total: total, version: VERSION }); });
        });
      }
      return Promise.all(PRECACHE.map(function (u) {
        return c.add(new Request(u, { cache: 'reload' })).then(function () { done++; tell(); });
      })).catch(function (error) {
        var discard = cacheExists ? Promise.resolve() : caches.delete(VERSION);
        return discard.then(function () {
          return self.clients.matchAll({ includeUncontrolled: true });
        }).then(function (cs) {
          cs.forEach(function (x) {
            x.postMessage({ type: 'dv-update-failed', message: 'Update files could not be downloaded. Check your connection and retry.' });
          });
          throw error;
        });
      });
    });
  }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (ks) {
    return Promise.all(ks.filter(function (k) { return k !== VERSION; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('message', function (e) {
  if (e.data === 'skip') self.skipWaiting();
  if (e.data === 'version' && e.source) e.source.postMessage({ type: 'dv-version', version: VERSION });
});

function keep(req, res) {
  if (!res || !(res.ok || res.type === 'opaque')) return;
  var copy = res.clone();
  caches.open(VERSION).then(function (c) { c.put(req, copy); });
}

self.addEventListener('fetch', function (e) {
  var r = e.request, u = new URL(r.url);
  if (r.method !== 'GET') return;
  if (u.origin !== location.origin && !CDN.test(r.url)) return; /* Odoo, GitHub and AI calls always go to the network */
  if (u.pathname.indexOf('/api/') !== -1) return;
  if (/\/version\.json$/.test(u.pathname) && u.searchParams.has('latest')) return; /* "what is the newest version?" always asks the server */

  if (r.mode === 'navigate') { /* pages: from the installed version, network only if never cached */
    e.respondWith(caches.match(r, { ignoreSearch: true }).then(function (m) {
      return m || fetch(r).then(function (res) { keep(r, res); return res; }).catch(function () { return caches.match('dashboard.html'); });
    }));
    return;
  }
  e.respondWith(caches.match(r).then(function (hit) { /* files: installed copy first; no silent background refresh */
    return hit || fetch(r).then(function (res) { keep(r, res); return res; });
  }));
});
